name: shopping_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

  assets:
    - assets/images/shoes_1.png
    - assets/images/shoes_2.png
    - assets/images/shoes_3.png
    - assets/images/shoes_4.png
